import {
  ArrowRight,
  Award,
  Backpack,
  BadgeCheck,
  BedDouble,
  BookOpen,
  Box,
  Building2,
  Bus,
  CalendarCheck,
  Check,
  ChevronRight,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Coffee,
  Cpu,
  DoorOpen,
  Dumbbell,
  FlaskConical,
  Footprints,
  GitBranch,
  GraduationCap,
  Home,
  Layers,
  LayoutGrid,
  Library,
  Magnet,
  Mail,
  MapPin,
  MapPinned,
  Megaphone,
  Microscope,
  Minus,
  Mountain,
  MousePointerClick,
  Music,
  Package,
  PencilLine,
  Phone,
  Plus,
  RotateCcw,
  Search,
  ShieldCheck,
  Sprout,
  Stethoscope,
  Trees,
  User,
  UserRoundCheck,
  Users,
  UsersRound,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";

// Content modules reference icons by their kebab-case Lucide names; this map
// keeps the bundle tree-shakeable (no lucide barrel import).
const iconMap: Record<string, LucideIcon> = {
  "arrow-right": ArrowRight,
  award: Award,
  backpack: Backpack,
  "badge-check": BadgeCheck,
  "bed-double": BedDouble,
  "book-open": BookOpen,
  box: Box,
  "building-2": Building2,
  bus: Bus,
  "calendar-check": CalendarCheck,
  check: Check,
  "chevron-right": ChevronRight,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  coffee: Coffee,
  cpu: Cpu,
  "door-open": DoorOpen,
  dumbbell: Dumbbell,
  "flask-conical": FlaskConical,
  footprints: Footprints,
  "git-branch": GitBranch,
  "graduation-cap": GraduationCap,
  home: Home,
  layers: Layers,
  "layout-grid": LayoutGrid,
  library: Library,
  magnet: Magnet,
  mail: Mail,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  megaphone: Megaphone,
  microscope: Microscope,
  minus: Minus,
  mountain: Mountain,
  "mouse-pointer-click": MousePointerClick,
  music: Music,
  package: Package,
  "pencil-line": PencilLine,
  phone: Phone,
  plus: Plus,
  "rotate-ccw": RotateCcw,
  search: Search,
  "shield-check": ShieldCheck,
  sprout: Sprout,
  stethoscope: Stethoscope,
  trees: Trees,
  user: User,
  "user-round-check": UserRoundCheck,
  users: Users,
  "users-round": UsersRound,
};

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Cmp = iconMap[name];
  if (!Cmp) throw new Error(`Unknown icon name: ${name}`);
  return <Cmp aria-hidden {...props} />;
}
